### ISSUE TITLE
Feature: Server Endpoints

### ISSUE THREAD

**Issue by Ost-Ethan** [Ost-Ethan/Final-Project-Ethan-Ostrowski#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Server Endpoints

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Endpoints for creating a user, logging in a user, writing a time to the times table, and getting times.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `data.sql` with pre-populated tables for users, scores, and games for testing.

### ☁️ Server Tasks
       Update server.ts with the following bulletpoints:
- [x] Create a "GET" endpoint that sends scores that match the speed Clicker game with no authMiddleware
- [x] Adjust the sql on the "GET" to join the users table at the userId, and ensure the response is only 20 (Or less) entries. 
- [x] Test the "GET" with HTTPie to ensure proper response.
- [x] Create a "POST" endpoint that posts a new time entry in the times table. Ensure it has AuthMiddleware. The SQL should use the userId from the db where req.user matches.
- [x] Ensure the "POST" endpoint responds with the entry that was posted.
- [x] Create a new "POST" endpoint for user creation. This does not require AuthMiddleware.
- [x] Ensure the User Creation "POST" request responds with a "createdAt" value from the entry in the db.
- [x] Create a new "POST" endpoint for user login, that creates and sends a JWT to the client. No authMiddleware.
- [x] Handle all errors and respond to the client using the provided error middleware.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
