### ISSUE TITLE
Speed Clicker Game Creation

### ISSUE THREAD

**Issue by Ost-Ethan** [Ost-Ethan/Final-Project-Ethan-Ostrowski#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can start and play the “Speed Clicker” game. (This game is a button and it must be clicked 10 times to complete the game, with the goal to click it as fast as possible.)

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to start and play the speed clicker game. The game end once the button is clicked 10 times.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/Ost-Ethan/Final-Project-Ethan-Ostrowski/assets/136650513/cbd94b11-00cf-4ece-85db-57a4dbad2dc7)
![image](https://github.com/Ost-Ethan/Final-Project-Ethan-Ostrowski/assets/136650513/17cc60ef-9467-4d9d-8208-979a45267554)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Create a component to draw the page header following the figma layout. Each item on the header should be a button.
- [x] Create a component for the start button and text,  following the figma. It should conditionally render based on a state called "isStarted". IsStarted can also be the key for the timer. 
- [x] Create a component for the clicker button, and text around it per the figma. It should have a title and a times clicked.
- [x] Create a counter component for the "Times clicked" text field.
- [x] Create a timer component that starts when the start button is pressed, and ends when the button counter is equal to 10. Display the timer as it updates. It should use the useState "isStarted" to hold onto the key to stop the setInterval. 
- [x] Use TailWind to format the page and ensure the layout is create correctly.

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
