### ISSUE TITLE
User can see the result of how much time it took to complete the “Speed Clicker” game.

### ISSUE THREAD

**Issue by Ost-Ethan** [Ost-Ethan/Final-Project-Ethan-Ostrowski#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see the result of how much time it took to complete the “Speed Clicker” game.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to see how long it took to complete the speed clicker game, Along with "Play again", and "Home Page" buttons and also a scoreboard that shows scores from the database.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/Ost-Ethan/Final-Project-Ethan-Ostrowski/assets/136650513/39cccc64-1b09-4fea-87bc-42bafea2295a)
![image](https://github.com/Ost-Ethan/Final-Project-Ethan-Ostrowski/assets/136650513/6691a47d-7e62-4a69-aa3b-856e3f79d3a9)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Create a component that contains the result information, the home button and the try again button, and the "log in to see your score on the leaderboard message. This component can use props to decide what message to display at the bottom, and what time to use for the display.
- [x] Create a scoreboard component to display entries of best times for the speed clicker game. The scoreboard component should have an useEffect that sends a request to the server for the information. It should then map through the response array, and create li elements for each score to display each entry.
- [x] Using Tailwind ensure that the layout matches the figma.

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
