### ISSUE TITLE
User can log in and store their times

### ISSUE THREAD

**Issue by Ost-Ethan** [Ost-Ethan/Final-Project-Ethan-Ostrowski#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users will be able to log in to store their times.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to create an account on an account page and it will be able to store their times to the database. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/Ost-Ethan/Final-Project-Ethan-Ostrowski/assets/136650513/2c30ce77-e844-4104-a38c-f4d0d19fb7f0)
![image](https://github.com/Ost-Ethan/Final-Project-Ethan-Ostrowski/assets/136650513/f5acc31c-65e3-468e-b128-9b9360a6872f)
![image](https://github.com/Ost-Ethan/Final-Project-Ethan-Ostrowski/assets/136650513/c2288ab7-2d4e-4ff1-b373-7968c6dc926d)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [ ] Create a component for the log in fields. Should send a fetch to the login server endpoint(POST).
- [ ] Create a component for the sign up field. Should send a fetch to the create user endpoint (POST). 
- [ ] In the response from the sign up or sign in, set the JWT token given from the response in sessionStorage, and also set the username in sessionStorage so that it can be accessed easily for the NavBar.
- [ ] Create a component for the log out button that replaces all log in buttons when a token is present in sessionStorage.
- [ ] When the log out button is clicked, make sure the token is removed from sessionStorage. 
- [ ] Ensure the formatting is correct per the figma.
- [ ] Ensure the user can be created in the database.
- [ ] Ensure the user can be authenticated with a JWT.

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
